"""create tables

Revision ID: 637f27d260b8
Revises: 
Create Date: 2026-03-19 09:20:14.328040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '637f27d260b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frog_game_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_key', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lugat_duel_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_key', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lugat_duel_questions_game_key'), 'lugat_duel_questions', ['game_key'], unique=False)
    op.create_index(op.f('ix_lugat_duel_questions_owner_user_id'), 'lugat_duel_questions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_lugat_duel_questions_subject'), 'lugat_duel_questions', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_key', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_game_key'), 'questions', ['game_key'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_is_public'), 'questions', ['is_public'], unique=False)
    op.create_index(op.f('ix_questions_owner_user_id'), 'questions', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_owner_user_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_public'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_game_key'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lugat_duel_questions_subject'), table_name='lugat_duel_questions')
    op.drop_index(op.f('ix_lugat_duel_questions_owner_user_id'), table_name='lugat_duel_questions')
    op.drop_index(op.f('ix_lugat_duel_questions_game_key'), table_name='lugat_duel_questions')
    op.drop_table('lugat_duel_questions')
    op.drop_table('frog_game_questions')
    # ### end Alembic commands ###